### ISSUE TITLE
Update Bug with blocks

### ISSUE THREAD

**Issue by Olybear9** [Olybear9/MultiVersion-PMMP#11]
Logging in on different versions causes blocks to be completely different when sent to the player, this needs fixing... bad...

**Comment by T14Raptor** [comment]
Seems the packet isn't translated at all still, even though it should. I'm going to look more into this.

**Comment by Olybear9** [comment]
Fixed in commit: https://github.com/Olybear9/MultiVersion-PMMP/commit/f3de33e8bc5cea3ca790d234bb46f6395188b64f
