### ISSUE TITLE
Update Skins

### ISSUE THREAD

**Issue by Olybear9** [Olybear9/MultiVersion-PMMP#18]
**Description:** While skins no longer crash clients, only 1.12 people can see 1.13 users. This needs some fixing.

**Proposal:** 
- [x] Add some functions that translate old legacy geometry to newer geometry. (possibly assign a fake skin?)
- [x] Fix encoding on `SkinListener` to support changes
- [x] Fix decoding to translate skins better.
- [x] Fix and clean up class references.

**Comment by ItzLightyHD** [comment]
Why do not set 1.13 skins visible as steve skins for 1.12? as hyperlands

**Comment by ItzLightyHD** [comment]
![image](https://user-images.githubusercontent.com/45460688/68870057-828b9d80-06fa-11ea-8b38-8fa9bbe9c6cc.png)

**Comment by Olybear9** [comment]
@ItzLightyHD 1.13 isn't supported yet make sure your PM is 1.12

**Comment by ItzLightyHD** [comment]
ok
