### ISSUE TITLE
Can you make it working on 1.13?

### ISSUE THREAD

**Issue by ItzLightyHD** [Olybear9/MultiVersion-PMMP#2]
**==DO NOT CHANGE ANYTHING BELOW THIS LINE==**
__Steps to complete:__
- [x] Complete rework of core
- [x] Update logins (Make a bypass for packets)
- [x] Add updated packets for 1.13 protocol
- [x] Make sure block mapping works on multiple versions
- [x] Fix any bugs

**Comment by Olybear9** [comment]
This does work on 1.13, I'm assuming you're asking if I can make it so 1.13 players can connect while your server is 1.12?

**Comment by ItzLightyHD** [comment]
Yes, because i tried to use PMMP 3.10.1 (Unofficial) and it's not working so well, then i want to use this to let people join on 1.13

**Comment by Olybear9** [comment]
I plan on making 1.13 compatible on 1.12 PM for the time being. I'm closing this and marking it as todo.

**Comment by Olybear9** [comment]
@ItzLightyHD  I suggest you watch this repo so you can get updates on what im doing :)

**Comment by Olybear9** [comment]
I'm an idiot and keep clicking close ffs

**Comment by Olybear9** [comment]
Closing as this has been virtually completed with the exception of skins

**Comment by ItzLightyHD** [comment]
so, can i enter on 1.13 too?

**Comment by Olybear9** [comment]
Yes however skins are qwerkie

**Comment by ItzLightyHD** [comment]
and making them show as steve for 1.12?

**Comment by Olybear9** [comment]
We're doing our best to get skins cross compatible

**Comment by ItzLightyHD** [comment]
ok, thanks
