### ISSUE TITLE
Internal Server Error When 1.12 Client Joins on 1.13 Server

### ISSUE THREAD

**Issue by jkorn2324** [Olybear9/MultiVersion-PMMP#20]
Error generates when a 1.12 client joins a 1.13 server; caused by the translateLogin() method in the 1.12 LoginPacket class not existing.

**Comment by Olybear9** [comment]
Known issue as we're working on 1.12  server support

**Comment by Olybear9** [comment]
Issue resolved with latest PM 1.13 release.
